// Do not edit this file; automatically generated by gulp.
'use strict';

this.IS_NODE_JS = !!(typeof module !== 'undefined' && module.exports);

this.BLOCKLY_DIR = (function(root) {
  if (!root.IS_NODE_JS) {
    // Find name of current directory.
    var scripts = document.getElementsByTagName('script');
    var re = new RegExp('(.+)[\/]blockly_(.*)uncompressed\.js$');
    for (var i = 0, script; script = scripts[i]; i++) {
      var match = re.exec(script.src);
      if (match) {
        return match[1];
      }
    }
    alert('Could not detect Blockly\'s directory name.');
  }
  return '';
})(this);

this.BLOCKLY_BOOT = function(root) {
  // Execute after Closure has loaded.
goog.addDependency('../../C:/blockly/client/core/block.js', ['Blockly.Block'], ['Blockly.Blocks', 'Blockly.Comment', 'Blockly.Connection', 'Blockly.FieldClickImage', 'Blockly.FieldScopeVariable', 'Blockly.Input', 'Blockly.Mutator', 'Blockly.Warning', 'Blockly.Workspace', 'Blockly.Xml', 'goog.array', 'goog.asserts', 'goog.math.Coordinate', 'goog.string']);
goog.addDependency('../../C:/blockly/client/core/block_svg.js', ['Blockly.BlockSvg'], ['Blockly.Block', 'Blockly.ContextMenu', 'goog.Timer', 'goog.asserts', 'goog.dom', 'goog.math.Coordinate']);
goog.addDependency('../../C:/blockly/client/core/blockly.js', ['Blockly'], ['Blockly.BlockSvg', 'Blockly.FieldAngle', 'Blockly.FieldCheckbox', 'Blockly.FieldColour', 'Blockly.FieldDropdown', 'Blockly.FieldImage', 'Blockly.FieldTextArea', 'Blockly.FieldTextInput', 'Blockly.FieldVariable', 'Blockly.Generator', 'Blockly.Msg', 'Blockly.Procedures', 'Blockly.Realtime', 'Blockly.Toolbox', 'Blockly.TypeBlock', 'Blockly.WidgetDiv', 'Blockly.WorkspaceSvg', 'Blockly.inject', 'Blockly.utils', 'goog.color', 'goog.events.KeyCodes', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/blocks.js', ['Blockly.Blocks'], []);
goog.addDependency('../../C:/blockly/client/core/bubble.js', ['Blockly.Bubble'], ['Blockly.Workspace', 'goog.dom', 'goog.math', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/comment.js', ['Blockly.Comment'], ['Blockly.Bubble', 'Blockly.Icon', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/connection.js', ['Blockly.Connection', 'Blockly.ConnectionDB'], ['goog.dom']);
goog.addDependency('../../C:/blockly/client/core/constants.js', ['Blockly.constants'], []);
goog.addDependency('../../C:/blockly/client/core/contextmenu.js', ['Blockly.ContextMenu'], ['goog.dom', 'goog.events', 'goog.events.KeyCodes', 'goog.events.KeyNames', 'goog.style', 'goog.ui.Menu', 'goog.ui.MenuItem']);
goog.addDependency('../../C:/blockly/client/core/css.js', ['Blockly.Css'], []);
goog.addDependency('../../C:/blockly/client/core/field.js', ['Blockly.Field'], ['goog.asserts', 'goog.dom', 'goog.math.Size', 'goog.style', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/field_angle.js', ['Blockly.FieldAngle'], ['Blockly.FieldTextInput', 'goog.math', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/field_checkbox.js', ['Blockly.FieldCheckbox'], ['Blockly.Field']);
goog.addDependency('../../C:/blockly/client/core/field_clickimage.js', ['Blockly.FieldClickImage'], ['Blockly.FieldImage']);
goog.addDependency('../../C:/blockly/client/core/field_colour.js', ['Blockly.FieldColour'], ['Blockly.Field', 'goog.dom', 'goog.events', 'goog.style', 'goog.ui.ColorPicker']);
goog.addDependency('../../C:/blockly/client/core/field_date.js', ['Blockly.FieldDate'], ['Blockly.Field', 'goog.date', 'goog.dom', 'goog.events', 'goog.i18n.DateTimeSymbols', 'goog.i18n.DateTimeSymbols_he', 'goog.style', 'goog.ui.DatePicker']);
goog.addDependency('../../C:/blockly/client/core/field_dropdown.js', ['Blockly.FieldDropdown'], ['Blockly.Field', 'goog.dom', 'goog.events', 'goog.style', 'goog.ui.Menu', 'goog.ui.MenuItem', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/field_image.js', ['Blockly.FieldImage'], ['Blockly.Field', 'goog.dom', 'goog.math.Size', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/field_label.js', ['Blockly.FieldLabel'], ['Blockly.Field', 'Blockly.Tooltip', 'goog.dom', 'goog.math.Size']);
goog.addDependency('../../C:/blockly/client/core/field_scope_variable.js', ['Blockly.FieldScopeVariable'], ['Blockly.FieldDropdown', 'Blockly.Msg', 'Blockly.ScopeVariables', 'goog.string']);
goog.addDependency('../../C:/blockly/client/core/field_textarea.js', ['Blockly.FieldTextArea'], ['Blockly.FieldTextInput', 'Blockly.Msg', 'goog.asserts', 'goog.dom', 'goog.events.KeyCodes', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/field_textinput.js', ['Blockly.FieldTextInput'], ['Blockly.Field', 'Blockly.Msg', 'goog.asserts', 'goog.dom', 'goog.events.KeyCodes', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/field_variable.js', ['Blockly.FieldVariable'], ['Blockly.FieldDropdown', 'Blockly.Msg', 'Blockly.Variables', 'goog.string']);
goog.addDependency('../../C:/blockly/client/core/flyout.js', ['Blockly.Flyout'], ['Blockly.Block', 'Blockly.Comment', 'Blockly.WorkspaceSvg', 'goog.dom', 'goog.events', 'goog.math.Rect', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/generator.js', ['Blockly.Generator'], ['Blockly.Block', 'goog.asserts']);
goog.addDependency('../../C:/blockly/client/core/icon.js', ['Blockly.Icon'], ['goog.dom']);
goog.addDependency('../../C:/blockly/client/core/inject.js', ['Blockly.inject'], ['Blockly.Css', 'Blockly.WorkspaceSvg', 'goog.dom', 'goog.ui.Component', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/input.js', ['Blockly.Input'], ['Blockly.Connection', 'Blockly.FieldLabel', 'goog.asserts']);
goog.addDependency('../../C:/blockly/client/core/msg.js', ['Blockly.Msg'], []);
goog.addDependency('../../C:/blockly/client/core/mutator.js', ['Blockly.Mutator'], ['Blockly.Bubble', 'Blockly.Icon', 'Blockly.WorkspaceSvg', 'goog.Timer', 'goog.dom']);
goog.addDependency('../../C:/blockly/client/core/names.js', ['Blockly.Names'], []);
goog.addDependency('../../C:/blockly/client/core/procedures.js', ['Blockly.Procedures'], ['Blockly.Field', 'Blockly.Names', 'Blockly.Workspace', 'Blockly.constants']);
goog.addDependency('../../C:/blockly/client/core/realtime-client-utils.js', ['rtclient'], []);
goog.addDependency('../../C:/blockly/client/core/realtime.js', ['Blockly.Realtime'], ['goog.array', 'goog.dom', 'goog.style', 'rtclient']);
goog.addDependency('../../C:/blockly/client/core/scopevariables.js', ['Blockly.ScopeVariables'], ['Blockly.Workspace', 'goog.string']);
goog.addDependency('../../C:/blockly/client/core/scrollbar.js', ['Blockly.Scrollbar', 'Blockly.ScrollbarPair'], ['goog.dom', 'goog.events']);
goog.addDependency('../../C:/blockly/client/core/toolbox.js', ['Blockly.Toolbox'], ['Blockly.Flyout', 'goog.dom', 'goog.events', 'goog.events.BrowserFeature', 'goog.html.SafeHtml', 'goog.math.Rect', 'goog.style', 'goog.ui.tree.TreeControl', 'goog.ui.tree.TreeNode']);
goog.addDependency('../../C:/blockly/client/core/tooltip.js', ['Blockly.Tooltip'], ['goog.dom']);
goog.addDependency('../../C:/blockly/client/core/trashcan.js', ['Blockly.Trashcan'], ['goog.Timer', 'goog.dom', 'goog.math', 'goog.math.Rect']);
goog.addDependency('../../C:/blockly/client/core/typeIndicator.js', [], []);
goog.addDependency('../../C:/blockly/client/core/typeblock.js', ['Blockly.TypeBlock', 'Blockly.TypeBlock.ac.AIArrayMatcher'], ['Blockly.Xml', 'goog.events', 'goog.events.KeyCodes', 'goog.events.KeyHandler', 'goog.iter', 'goog.string', 'goog.string', 'goog.style', 'goog.ui.ac', 'goog.ui.ac.ArrayMatcher', 'goog.ui.ac.AutoComplete', 'goog.ui.ac.InputHandler', 'goog.ui.ac.Renderer']);
goog.addDependency('../../C:/blockly/client/core/utils.js', ['Blockly.utils'], ['goog.dom', 'goog.events.BrowserFeature', 'goog.math.Coordinate', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/variables.js', ['Blockly.Variables'], ['Blockly.Workspace', 'Blockly.constants', 'goog.string']);
goog.addDependency('../../C:/blockly/client/core/warning.js', ['Blockly.Warning'], ['Blockly.Bubble', 'Blockly.Icon']);
goog.addDependency('../../C:/blockly/client/core/widgetdiv.js', ['Blockly.WidgetDiv'], ['Blockly.Css', 'goog.dom', 'goog.style']);
goog.addDependency('../../C:/blockly/client/core/workspace.js', ['Blockly.Workspace'], ['goog.math']);
goog.addDependency('../../C:/blockly/client/core/workspace_svg.js', ['Blockly.WorkspaceSvg'], ['Blockly.ScrollbarPair', 'Blockly.Trashcan', 'Blockly.Workspace', 'Blockly.Xml', 'Blockly.ZoomControls', 'goog.dom', 'goog.math.Coordinate', 'goog.userAgent']);
goog.addDependency('../../C:/blockly/client/core/xml.js', ['Blockly.Xml'], ['goog.dom']);
goog.addDependency('../../C:/blockly/client/core/zoom_controls.js', ['Blockly.ZoomControls'], ['goog.dom']);
goog.addDependency("base.js", [], []);

// Load Blockly.
goog.require('Blockly.requires');

delete root.BLOCKLY_DIR;
delete root.BLOCKLY_BOOT;
delete root.IS_NODE_JS;
};

if (this.IS_NODE_JS) {
  this.BLOCKLY_BOOT(this);
  module.exports = Blockly;
} else {
  document.write('<script src="' + this.BLOCKLY_DIR +
      '/closure/goog/base.js"></script>');
  document.write('<script>this.BLOCKLY_BOOT(this);</script>');
}
